export { SUCCESSFUL_REGISTER,
  SUCCESSFUL_LOGIN, SUCCESSFUL_ADD_ARTICLE, SUCCESSFUL_EDIT_ARTICLE, SUCCESSFUL_DELETE_ARTICLE,
  SUCCESSFUL_PWD_RECOVER, SUCCESSFUL_ADDING, SUCCESSFUL_DELETE, SUCCESSFUL_EDIT
 } from './notices'

  export { BASE_URL } from './base_url'
 
 export { ERROR_LOGIN, 
  ERROR_PWD_RECOVER, ERROR_ARTICLE_ADD, ERROR_ARTICLE_DELETE, ERROR_ARTICLE_EDIT,
  ERROR_REGISTER, ERROR_lANG_ADDIND , ERROR_LANG_DELETE, ERROR_LANG_EDIT
 } from './errors'

 export { EMPTY_FIELD, 
  WRONG_TYPE, 
  MANY_SYMBOLS, 
  FEW_SYMBOLS, 
  NOT_EMAIL, 
  PASSWORD_ERROR
 } from './inputValidMasseges'
 
export {errorHandler} from './errorHandler.tsx'

export {
  MAX_WIDTH__MD,
  MAX_WIDTH_LG,
  MAX_WIDTH_SM,
  MAX_WIDTH_XL,
  MAX_WIDTH_XXL,
} from './breakpoints.tsx'

export {CONTENT_NAVIGATION_MENU} from './contentNavMenu.ts'